[package]
name = "samply"
version = "0.9.0"
authors = ["Markus Stange <mstange@themasta.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A command line profiler for macOS and Linux."
repository = "https://github.com/mstange/samply/"
readme = "README.md"

[dependencies]

samply-symbols = { version = "0.17", path = "../samply-symbols" }
samply-server = { version = "0.14", path = "../samply-server" }
fxprof-processed-profile = { version = "0.4", path = "../fxprof-processed-profile" }
# framehop = { path = "../../framehop" }
framehop = "0.7"
# linux-perf-data = { path = "../../linux-perf-data" }
linux-perf-data = "0.6.0"

tokio = { version = "1.17.0", features = ["rt", "rt-multi-thread", "macros"] }
clap = { version = "3.2", features = ["derive"] }
byteorder = "1.4.3"
debugid = "0.8.0"
memchr = "2.4.1"
memmap2 = "0.5.3"
object = "0.29"
serde_json = "1.0.53"
thiserror = "1.0.19"
tempfile = "3.1.0"

[target.'cfg(any(target_os = "macos", target_os = "linux"))'.dependencies]

# uuid = "1.0.0"
libc = "0.2.71"
crossbeam-channel = "0.5.4"
signal-hook = "0.3.9"

[target.'cfg(target_os = "macos")'.dependencies]

perfrecord-mach-ipc-rendezvous = { version = "0.2.1", path = "../perfrecord-mach-ipc-rendezvous" }

uuid = "1.0.0"
mach = "0.3.2"
flate2 = "1.0.23"

[target.'cfg(target_os = "linux")'.dependencies]

parking_lot = "0.12.1"
num_cpus = "1.13.1"
uname = "0.1.1"
nix = "0.24.2"

[profile.release]
debug = true
panic = "abort"
