[package]
name = "samply-api"
version = "0.18.0"
authors = ["Markus Stange <mstange.moz@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
description = "JSON API for querying symbol information, uses samply-symbols."
repository = "https://github.com/mstange/samply/"
readme = "README.md"

[features]
default = []
send_futures = ["samply-symbols/send_futures"]

[dependencies]
samply-symbols = { version = "0.17.1", path = "../samply-symbols" }
thiserror = "1.0.26"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
serde-hex = "0.1.0"
serde_tuple = "0.5.0"
yaxpeax-arch = "0.2.7"
yaxpeax-x86 = "1.1.4"
yaxpeax-arm = "0.2.3"

[dev-dependencies]
memmap2 = "0.5.0"
anyhow = "1.0.28"
futures = "0.3.5"
assert-json-diff = "2.0.1"
serde_json = "1.0.68"
